INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AF', 'AFG', 004, 'Afeganistão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ZA', 'ZAF', 710, 'África do Sul');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AX', 'ALA', 248, 'Åland, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AL', 'ALB', 008, 'Albânia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('DE', 'DEU', 276, 'Alemanha');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AD', 'AND', 020, 'Andorra');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AO', 'AGO', 024, 'Angola');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AI', 'AIA', 660, 'Anguilla');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AQ', 'ATA', 010, 'Antárctida');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AG', 'ATG', 028, 'Antigua e Barbuda');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AN', 'ANT', 530, 'Antilhas Holandesas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SA', 'SAU', 682, 'Arábia Saudita');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('DZ', 'DZA', 012, 'Argélia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AR', 'ARG', 032, 'Argentina');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AM', 'ARM', 051, 'Arménia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AW', 'ABW', 533, 'Aruba');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AU', 'AUS', 036, 'Austrália');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AT', 'AUT', 040, 'Áustria');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AZ', 'AZE', 031, 'Azerbeijão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BS', 'BHS', 044, 'Bahamas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BH', 'BHR', 048, 'Bahrain');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BD', 'BGD', 050, 'Bangladesh');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BB', 'BRB', 052, 'Barbados');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BE', 'BEL', 056, 'Bélgica');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BZ', 'BLZ', 084, 'Belize');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BJ', 'BEN', 204, 'Benin');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BM', 'BMU', 060, 'Bermuda');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BY', 'BLR', 112, 'Bielo-Rússia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BO', 'BOL', 068, 'Bolívia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BA', 'BIH', 070, 'Bósnia-Herzegovina');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BW', 'BWA', 072, 'Botswana');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BV', 'BVT', 074, 'Bouvet, Ilha');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BR', 'BRA', 076, 'Brasil');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BN', 'BRN', 096, 'Brunei');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BG', 'BGR', 100, 'Bulgária');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BF', 'BFA', 854, 'Burkina Faso');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BI', 'BDI', 108, 'Burundi');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('BT', 'BTN', 064, 'Butão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CV', 'CPV', 132, 'Cabo Verde');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KH', 'KHM', 116, 'Cambodja');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CM', 'CMR', 120, 'Camarões');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CA', 'CAN', 124, 'Canadá');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KY', 'CYM', 136, 'Cayman, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KZ', 'KAZ', 398, 'Cazaquistão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CF', 'CAF', 140, 'Centro-africana, República');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TD', 'TCD', 148, 'Chade');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CZ', 'CZE', 203, 'Checa, República');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CL', 'CHL', 152, 'Chile');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CN', 'CHN', 156, 'China');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CY', 'CYP', 196, 'Chipre');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CX', 'CXR', 162, 'Christmas, Ilha');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CC', 'CCK', 166, 'Cocos, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CO', 'COL', 170, 'Colômbia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KM', 'COM', 174, 'Comores');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CG', 'COG', 178, 'Congo, República do');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CD', 'COD', 180, 'Congo, República Democrática do (antigo Zaire)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CK', 'COK', 184, 'Cook, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KR', 'KOR', 410, 'Coreia do Sul');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KP', 'PRK', 408, 'Coreia, República Democrática da (Coreia do Norte)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CI', 'CIV', 384, 'Costa do Marfim');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CR', 'CRI', 188, 'Costa Rica');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('HR', 'HRV', 191, 'Croácia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CU', 'CUB', 192, 'Cuba');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('DK', 'DNK', 208, 'Dinamarca');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('DJ', 'DJI', 262, 'Djibouti');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('DM', 'DMA', 212, 'Dominica');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('DO', 'DOM', 214, 'Dominicana, República');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('EG', 'EGY', 818, 'Egipto');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SV', 'SLV', 222, 'El Salvador');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AE', 'ARE', 784, 'Emiratos Árabes Unidos');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('EC', 'ECU', 218, 'Equador');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ER', 'ERI', 232, 'Eritreia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SK', 'SVK', 703, 'Eslováquia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SI', 'SVN', 705, 'Eslovénia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ES', 'ESP', 724, 'Espanha');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('US', 'USA', 840, 'Estados Unidos da América');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('EE', 'EST', 233, 'Estónia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ET', 'ETH', 231, 'Etiópia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('FO', 'FRO', 234, 'Faroe, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('FJ', 'FJI', 242, 'Fiji');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PH', 'PHL', 608, 'Filipinas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('FI', 'FIN', 246, 'Finlândia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('FR', 'FRA', 250, 'França');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GA', 'GAB', 266, 'Gabão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GM', 'GMB', 270, 'Gâmbia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GH', 'GHA', 288, 'Gana');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GE', 'GEO', 268, 'Geórgia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GS', 'SGS', 239, 'Geórgia do Sul e Sandwich do Sul, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GI', 'GIB', 292, 'Gibraltar');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GR', 'GRC', 300, 'Grécia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GD', 'GRD', 308, 'Grenada');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GL', 'GRL', 304, 'Gronelândia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GP', 'GLP', 312, 'Guadeloupe');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GU', 'GUM', 316, 'Guam');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GT', 'GTM', 320, 'Guatemala');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GG', 'GGY', 831, 'Guernsey');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GY', 'GUY', 328, 'Guiana');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GF', 'GUF', 254, 'Guiana Francesa');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GW', 'GNB', 624, 'Guiné-Bissau');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GN', 'GIN', 324, 'Guiné-Conacri');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GQ', 'GNQ', 226, 'Guiné Equatorial');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('HT', 'HTI', 332, 'Haiti');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('HM', 'HMD', 334, 'Heard e Ilhas McDonald, Ilha');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('HN', 'HND', 340, 'Honduras');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('HK', 'HKG', 344, 'Hong Kong');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('HU', 'HUN', 348, 'Hungria');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('YE', 'YEM', 887, 'Iémen');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IN', 'IND', 356, 'Índia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ID', 'IDN', 360, 'Indonésia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IQ', 'IRQ', 368, 'Iraque');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IR', 'IRN', 364, 'Irão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IE', 'IRL', 372, 'Irlanda');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IS', 'ISL', 352, 'Islândia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IL', 'ISR', 376, 'Israel');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IT', 'ITA', 380, 'Itália');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('JM', 'JAM', 388, 'Jamaica');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('JP', 'JPN', 392, 'Japão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('JE', 'JEY', 832, 'Jersey');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('JO', 'JOR', 400, 'Jordânia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KI', 'KIR', 296, 'Kiribati');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KW', 'KWT', 414, 'Kuwait');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LA', 'LAO', 418, 'Laos');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LS', 'LSO', 426, 'Lesoto');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LV', 'LVA', 428, 'Letónia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LB', 'LBN', 422, 'Líbano');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LR', 'LBR', 430, 'Libéria');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LY', 'LBY', 434, 'Líbia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LI', 'LIE', 438, 'Liechtenstein');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LT', 'LTU', 440, 'Lituânia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LU', 'LUX', 442, 'Luxemburgo');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MO', 'MAC', 446, 'Macau');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MK', 'MKD', 807, 'Macedónia, República da');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MG', 'MDG', 450, 'Madagáscar');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MY', 'MYS', 458, 'Malásia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MW', 'MWI', 454, 'Malawi');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MV', 'MDV', 462, 'Maldivas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ML', 'MLI', 466, 'Mali');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MT', 'MLT', 470, 'Malta');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('FK', 'FLK', 238, 'Malvinas, Ilhas (Falkland)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IM', 'IMN', 833, 'Man, Ilha de');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MP', 'MNP', 580, 'Marianas Setentrionais');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MA', 'MAR', 504, 'Marrocos');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MH', 'MHL', 584, 'Marshall, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MQ', 'MTQ', 474, 'Martinica');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MU', 'MUS', 480, 'Maurícia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MR', 'MRT', 478, 'Mauritânia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('YT', 'MYT', 175, 'Mayotte');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('UM', 'UMI', 581, 'Menores Distantes dos Estados Unidos, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MX', 'MEX', 484, 'México');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MM', 'MMR', 104, 'Myanmar (antiga Birmânia)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('FM', 'FSM', 583, 'Micronésia, Estados Federados da');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MZ', 'MOZ', 508, 'Moçambique');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MD', 'MDA', 498, 'Moldávia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MC', 'MCO', 492, 'Mónaco');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MN', 'MNG', 496, 'Mongólia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ME', 'MNE', 499, 'Montenegro');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('MS', 'MSR', 500, 'Montserrat');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NA', 'NAM', 516, 'Namíbia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NR', 'NRU', 520, 'Nauru');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NP', 'NPL', 524, 'Nepal');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NI', 'NIC', 558, 'Nicarágua');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NE', 'NER', 562, 'Níger');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NG', 'NGA', 566, 'Nigéria');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NU', 'NIU', 570, 'Niue');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NF', 'NFK', 574, 'Norfolk, Ilha');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NO', 'NOR', 578, 'Noruega');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NC', 'NCL', 540, 'Nova Caledónia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NZ', 'NZL', 554, 'Nova Zelândia (Aotearoa)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('OM', 'OMN', 512, 'Oman');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('NL', 'NLD', 528, 'Países Baixos (Holanda)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PW', 'PLW', 585, 'Palau');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PS', 'PSE', 275, 'Palestina');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PA', 'PAN', 591, 'Panamá');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PG', 'PNG', 598, 'Papua-Nova Guiné');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PK', 'PAK', 586, 'Paquistão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PY', 'PRY', 600, 'Paraguai');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PE', 'PER', 604, 'Peru');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PN', 'PCN', 612, 'Pitcairn');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PF', 'PYF', 258, 'Polinésia Francesa');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PL', 'POL', 616, 'Polónia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PR', 'PRI', 630, 'Porto Rico');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PT', 'PRT', 620, 'Portugal');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('QA', 'QAT', 634, 'Qatar');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KE', 'KEN', 404, 'Quénia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KG', 'KGZ', 417, 'Quirguistão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('GB', 'GBR', 826, 'Reino Unido da Grã-Bretanha e Irlanda do Norte');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('RE', 'REU', 638, 'Reunião');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('RO', 'ROU', 642, 'Roménia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('RW', 'RWA', 646, 'Ruanda');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('RU', 'RUS', 643, 'Rússia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('EH', 'ESH', 732, 'Saara Ocidental');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('AS', 'ASM', 016, 'Samoa Americana');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('WS', 'WSM', 882, 'Samoa (Samoa Ocidental)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('PM', 'SPM', 666, 'Saint Pierre et Miquelon');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SB', 'SLB', 090, 'Salomão, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('KN', 'KNA', 659, 'São Cristóvão e Névis (Saint Kitts e Nevis)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SM', 'SMR', 674, 'San Marino');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ST', 'STP', 678, 'São Tomé e Príncipe');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('VC', 'VCT', 670, 'São Vicente e Granadinas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SH', 'SHN', 654, 'Santa Helena');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LC', 'LCA', 662, 'Santa Lúcia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SN', 'SEN', 686, 'Senegal');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SL', 'SLE', 694, 'Serra Leoa');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('RS', 'SRB', 688, 'Sérvia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SC', 'SYC', 690, 'Seychelles');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SG', 'SGP', 702, 'Singapura');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SY', 'SYR', 760, 'Síria');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SO', 'SOM', 706, 'Somália');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('LK', 'LKA', 144, 'Sri Lanka');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SZ', 'SWZ', 748, 'Suazilândia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SD', 'SDN', 736, 'Sudão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SE', 'SWE', 752, 'Suécia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('CH', 'CHE', 756, 'Suíça');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SR', 'SUR', 740, 'Suriname');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('SJ', 'SJM', 744, 'Svalbard e Jan Mayen');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TH', 'THA', 764, 'Tailândia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TW', 'TWN', 158, 'Taiwan');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TJ', 'TJK', 762, 'Tajiquistão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TZ', 'TZA', 834, 'Tanzânia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TF', 'ATF', 260, 'Terras Austrais e Antárticas Francesas (TAAF)');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('IO', 'IOT', 086, 'Território Britânico do Oceano Índico');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TL', 'TLS', 626, 'Timor-Leste');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TG', 'TGO', 768, 'Togo');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TK', 'TKL', 772, 'Toquelau');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TO', 'TON', 776, 'Tonga');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TT', 'TTO', 780, 'Trindade e Tobago');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TN', 'TUN', 788, 'Tunísia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TC', 'TCA', 796, 'Turks e Caicos');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TM', 'TKM', 795, 'Turquemenistão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TR', 'TUR', 792, 'Turquia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('TV', 'TUV', 798, 'Tuvalu');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('UA', 'UKR', 804, 'Ucrânia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('UG', 'UGA', 800, 'Uganda');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('UY', 'URY', 858, 'Uruguai');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('UZ', 'UZB', 860, 'Usbequistão');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('VU', 'VUT', 548, 'Vanuatu');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('VA', 'VAT', 336, 'Vaticano');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('VE', 'VEN', 862, 'Venezuela');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('VN', 'VNM', 704, 'Vietname');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('VI', 'VIR', 850, 'Virgens Americanas, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('VG', 'VGB', 092, 'Virgens Britânicas, Ilhas');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('WF', 'WLF', 876, 'Wallis e Futuna');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ZM', 'ZMB', 894, 'Zâmbia');
INSERT INTO public.pais (isobinario, isoternario, codigo, nome) VALUES  ('ZW', 'ZWE', 716, 'Zimbabwe');